FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY app ./app
COPY next.config.js ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

# standalone output
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
