name: Build Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Image
        run: docker build -t cost-detective-api ./apps/api

      - name: Build Web Image
        run: docker build -t cost-detective-web ./dashboard